{% set version = '1.8-2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-zoo
  version: {{ version|replace("-", "_") }}

source:
  fn: zoo_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/zoo_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/zoo/zoo_{{ version }}.tar.gz
  sha256: 7dd315290def0ea6b6f127290d9e769e54cd98668f2898fb104c9758fb8bfcd2

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
  host:
    - r-base
    - r-lattice >=0.20_27
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-lattice >=0.20_27

test:
  commands:
    - $R -e "library('zoo')"           # [not win]
    - "\"%R%\" -e \"library('zoo')\""  # [win]

about:
  home: http://zoo.R-Forge.R-project.org/
  license: GPL-2 | GPL-3
  summary: An S3 class with methods for totally ordered indexed observations. It is particularly
    aimed at irregular time series of numeric vectors/matrices and factors. zoo's key
    design goals are independence of a particular index/date/time class and consistency
    with ts and base R by providing methods to extend standard generics.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - croth1
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
