travis:
  secure:
    BINSTAR_TOKEN: ZhlYJ0kZv2wd4UId1ooVyJREZb1rESS2ljK8gAKtYdePkR6mCrWxfFeKhFZ5M3XR5sYeVbxYyIzIy33fpW4PYo3jWQDFsiVFyYtF4qwQn7aXAGCzyV8lO4EJsocFpdm1vyTmJ9X4C1HpkwPQX2m62gRLIo9Jku5QumYRQNqL8ShHpf9cYlDjlGzvk7ZCm7zG+poZO65klvLrE6ayPPCelsIXO2e4Xc+EQI8BHhDmyBZzrWNDlP2tkRJ+ojZwtv+MAKo2E77bsOzvQA5vfTRc0s1hUxu0bPFU5yfVAW335Dlj4LPHsUgNTHQrx+9VaHiPZuglJ19bpjm6vvMAtf8KO/5iQHWTWwVYib3DO81ZcbpkiB0WhXXreJhI6xN38Q+xlWFbhDoxyi8Mk542jZTvmtuGnIM6fYUBGEY0V7GsmUqiRMUjrAVP08hVcqlz5kzhOINMaMfq82tFLcBVHzlaxDojCXJtYBhOh52gE6t3EhCIvVO5NprvepSEO60YsQbjf7OFUHJnOag8kTo1CrMaTC1qS/3Ujsasxrt3PkmMtwaLw8NtpXZxPTM36BNrDfsiJn0IIJGfG5GDN8U02KXDhkCZeXO52AVteY/Pgnit28rftSPSqZ7KILsMznMc2t+XXz0zcCPTPiNbh2z1sv88KC/WLhQHitqYTvI5ONiwrKI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
